export const partAbbr = {
  bonnet: 'bnt',
  bumper: 'bpr',
  door_front_left: 'dfl',
  door_front_right: 'dfr',
  door_rear_left: 'drl',
  door_rear_right: 'drr',
  fender_front_left: 'ffl',
  fender_front_right: 'ffr',
  fender_rear_left: 'frl',
  fender_rear_right: 'frr',
  headlight_left: 'hll',
  headlight_right: 'hlr',
  mirror_front_left: 'mfl',
  mirror_front_right: 'mfr',

  panel_roof: 'prf',
  quarter_window_front_left: 'qwfl',
  quarter_window_front_right: 'qwfr',
  quarter_window_rear_left: 'qwrl',
  quarter_window_rear_right: 'qwrr',

  rear_bumper: 'rbp',
  rear_windshield: 'rws',
  running_board_left: 'rbl',
  running_board_right: 'rbr',

  side_panel_cargo_left: 'spcl',
  side_panel_cargo_right: 'spcr',

  tail_light_left: 'tll',
  tail_light_right: 'tlr',
  trunk_cover: 'tcv',

  tyre_front_left: 'tyfl',
  tyre_front_right: 'tyfr',
  tyre_rear_left: 'tyrl',
  tyre_rear_right: 'tyrr',

  wheel_front_left: 'wfl',
  wheel_front_right: 'wfr',
  wheel_rear_left: 'wrl',
  wheel_rear_right: 'wrr',
  window_front_left: 'ofl',
  window_front_right: 'ofr',
  window_rear_left: 'orl',
  window_rear_right: 'orr',
  windshield: 'wsh',
  bumper_upper: 'ubpr',
  bumper_lower: 'lbpr',

  moulding_side_panel_left: 'mspl',
  moulding_side_panel_right: 'mspr',
  foot_step_left: 'fsl',
  foot_step_right: 'fsr',
  moulding_door_front_left: 'mdfl',
  moulding_door_front_right: 'mdfr',
  moulding_door_rear_left: 'mdrl',
  moulding_door_rear_right: 'mdrr',
  moulding_fender_front_left: 'mffl',
  moulding_fender_front_right: 'mffr',
  moulding_fender_rear_left: 'mfrl',
  moulding_fender_rear_right: 'mfrr',
  moulding_running_board_left: 'mrbl',
  moulding_running_board_right: 'mrbr',
};
