export const parts = [
  'bonnet',
  'bumper',
  'door_front_left',
  'door_front_right',
  'door_rear_left',
  'door_rear_right',
  'fender_front_left',
  'fender_front_right',
  'fender_rear_left',
  'fender_rear_right',
  'headlight_left',
  'headlight_right',
  'mirror_front_left',
  'mirror_front_right',

  'panel_roof',
  'quarter_window_front_left',
  'quarter_window_front_right',
  'quarter_window_rear_left',
  'quarter_window_rear_right',

  'rear_bumper',
  'rear_windshield',
  'running_board_left',
  'running_board_right',

  'side_panel_cargo_left',
  'side_panel_cargo_right',

  'tail_light_left',
  'tail_light_right',
  'trunk_cover',

  'tyre_front_left',
  'tyre_front_right',
  'tyre_rear_left',
  'tyre_rear_right',

  'bumper_upper',
  'bumper_lower',

  'wheel_front_left',
  'wheel_front_right',
  'wheel_rear_left',
  'wheel_rear_right',
  'window_front_left',
  'window_front_right',
  'window_rear_left',
  'window_rear_right',
  'windshield',

  'moulding_side_panel_left',
  'moulding_side_panel_right',
  'foot_step_left',
  'foot_step_right',
  'moulding_door_front_left',
  'moulding_door_front_right',
  'moulding_door_rear_left',
  'moulding_door_rear_right',
  'moulding_fender_front_left',
  'moulding_fender_front_right',
  'moulding_fender_rear_left',
  'moulding_fender_rear_right',
  'moulding_running_board_left',
  'moulding_running_board_right',
];
